
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` (que corre en el postinstall de cada `npm install`, incluido en Vercel)
// no necesita conexión a la base de datos — solo lee el esquema. Usamos process.env directo
// (en vez del helper `env()` de Prisma, que lanza un error si la variable no existe) para que
// generate nunca falle por esto; db push/migrate sí necesitan las variables reales al correr.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL,
    directUrl: process.env.DIRECT_URL,
  },
});
